# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='htmltext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
